config/routes.rb
Rails.application.routes.draw do
devise_for :users
 resources :recipes
 get "/search", to: 'pages#search', :as => 'search_page'
 root "recipes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base


	has_many :ingredients
	has_many :directions
	belongs_to :user
	accepts_nested_attributes_for :ingredients,
  															reject_if: proc { |attributes| attributes['name'].blank? },
  															allow_destroy: true
 	accepts_nested_attributes_for :directions,
  															reject_if: proc { |attributes| attributes['step'].blank? },
  															allow_destroy: true

  validates :title, :description, :image, presence: true

	has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	
end

app/models/user.rb
class User < ApplicationRecord


  include Gravtastic
    gravtastic

    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!") and return

  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show
	end


	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Successfully created new recipe"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted recipe"
	end



	private

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html></html>
<head>
  <title>Recipe App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Recipe Box", root_path %>
      </div>

      <%= form_tag(search_page_path, :method => "get",
          class: 'navbar-form navbar-left') do %>
        <div class="input-group">
          <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
          <div class="input-group-btn">
            <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
          </div>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= image_tag current_user.gravatar_url, :class => "gravatar" %></li>
          <li>
            <%= link_to "New Recipe", new_recipe_path %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>


  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert" %>
    <% end %>



    <%= yield %>
  </div>


  <footer class="container-fluid text-center" style="  background-color: #d9d9d9;color: black;padding: 15px;       margin-top: 15px;">
       <div>
      Our Recipes Website is Offering you above these Orders.
       <br>
       No 1509, 15 Floor,Sakura Tower<br>
       yangonpress@gmail.com<br>
       Ph: 0918848225 <br>
       <div>
           <div class="row">
             <div class="col-sm-4">
               <a href="/juices"><h5>Juice</h5></a>
               We offering You These Orders<br>
               We admit that the Food are really good Quality <br>
             </div>
             <div class="col-sm-4">
               <a href="/meals"><h5>Meals</h5></a>
               <%= Time.now.year %><br>
               We offering You These Orders<br>
               We admit that the  are Juices really good Quality and Healthy for you.<br>
             </div>
             <div class="col-sm-4">
               <h5>Social</h5>
               <a href="https://www.facebook.com/"><p>Facebook</p></a>
               <a href="https://www.instagram.com/">
                 <p>Instagram</p>
               </a>
               <a href="https://www.google.com/"><p>Google</p></a>

             </div>
           </div>
         </div>
       </div>





     </footer>
</body>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="errors">
      <p>
        <%= @recipe.errors.count %>
        Prevented this recipe froms saving
      </p>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :image, input_html: { class: 'form-control' } %>
    <div class="row">
      <div class="col-md-6">
        <h3>Ingredients</h3>
        <div id="ingredients">
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', f: ingredient %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h3>Directions</h3>
        <div id="directions">
          <%= f.simple_fields_for :directions do |direction| %>
            <%= render 'direction_fields', f: direction %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form' %>

app/views/recipes/index.html.erb

<div id="splash" class="splash">

  <div class="splash__brand">
      <a title="Recipe Box" href="/"><%= image_tag("logo.png", class: "menu_icon" )%></a>

  </div>


<% @recipe.each_slice(3) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to recipe do %>
              <%= image_tag recipe.image.url(:medium) %>
            <% end %>
          </div>
          <h2>
            <%= link_to recipe.title, recipe %>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>
<br/>
<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/recipes/show.html.erb
<div class="main_content">
  <div class="row" id="recipe_top">
    <div class="col-md-4">
      <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
    </div>
    <div class="col-md-8">
      <div id="recipe_info">
        <h1>
          <%= @recipe.title %>
        </h1>
        <h4>
          <%= @recipe.user.email %>
        </h4>
        <h5>
          <%= @recipe.created_at %>
        </h5>
        <p class="description">
          <%= @recipe.description %>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div id="directions">
        <h2>Directions</h2>
        <ul>
          <% @recipe.directions.each do |direction| %>
            <li>
              <%= direction.step %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <% if user_signed_in? %>
        <%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
        <%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>